import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const root=process.env.BOM_ROOT || path.dirname(fileURLToPath(import.meta.url));
const record=JSON.parse(await fs.readFile(path.join(root,'parts-sources.json'),'utf8'));
const rows=record.bom.rows;
const wb=Workbook.create();const sh=wb.worksheets.add('BOM');
sh.showGridLines=false;
const last=9+rows.length;
sh.getRange(`A1:O${last}`).format.font={name:'Arial',size:10,color:'#203444'};
sh.mergeCells('A1:O1');sh.getRange('A1').values=[['ROLLER-300  |  FIRST INDOOR BUILD']];
sh.getRange('A1:O1').format={fill:'#203F4B',font:{name:'Arial',size:20,bold:true,color:'#FFFFFF'},rowHeight:38};
sh.mergeCells('A2:O2');sh.getRange('A2').values=[['Owned INJORA INJS035-360 locked. Complete shell and hatch with ONE populated drive. No new servo/programmer purchase. Powered release held.']];
sh.getRange('A2:O2').format={fill:'#DFECEC',rowHeight:29,font:{name:'Arial',size:11,color:'#203F4B'}};
sh.mergeCells('A3:D3');sh.getRange('A3').values=[['PRICED FIRST-PURCHASE SUBTOTAL']];
sh.getRange('E3').formulas=[[`=SUM(K10:K${last})`]];
sh.getRange('E3').setNumberFormat('$0.00');
sh.mergeCells('F3:O3');sh.getRange('F3').values=[['USD; excludes tax, delivery, shaft preparation and every blank-price / HOLD item. This is not a vehicle total.']];
sh.getRange('A3:O3').format.rowHeight=28;
sh.getRange('A3:E3').format.fill='#D8EDE4';sh.getRange('E3').format.font={bold:true,size:16,color:'#1D5A44'};
for(const [row,txt] of [[4,'Blue cells are editable quantities/prices. Vehicle quantities are planning counts; blank means unresolved. Owned quantities not confirmed remain blank.'],[5,'Buy qty = max(first-stage target − owned − already ordered, 0). Pack count rounds up. Enter confirmed purchases in Owned / Ordered.'],[6,'Canonical record: parts-sources.json. Return workbook edits there before regeneration. Sources and sizing/hold reasons are alongside each row.'],[7,'Priority: reusable wheel support / servo → belt and real limiter → front sensors / cameras → battery, Pixracer, Pi and retained harness.']]){
 sh.mergeCells(`A${row}:O${row}`);sh.getRange(`A${row}`).values=[[txt]];sh.getRange(`A${row}:O${row}`).format.rowHeight=24;
}
sh.getRange('A9:O9').values=[['ID','Part / exact model','Stage','Vehicle qty','First target','Owned','Ordered','Buy qty','Pack qty','Pack USD','Buy USD','Source','Checked','Reason / sizing / purchase gate','Group']];
sh.getRange(`A10:O${last}`).values=rows.map(q=>[q.id,`${q.item}\n${q.model}`,q.stage,q.vehicle_qty,q.first_stage_qty,q.owned_qty,q.ordered_qty,null,q.pack_qty,q.pack_price_usd,null,q.source,q.checked,q.notes,q.group]);
sh.getRange(`H10:H${last}`).formulas=rows.map((q,i)=>[`=IF(E${i+10}=0,0,MAX(E${i+10}-F${i+10}-G${i+10},0))`]);
sh.getRange(`K10:K${last}`).formulas=rows.map((q,i)=>[`=IF(H${i+10}=0,0,IF(ISNUMBER(J${i+10}),ROUNDUP(H${i+10}/I${i+10},0)*J${i+10},""))`]);
const table=sh.tables.add(`A9:O${last}`,true,'RollerBOM');table.showFilterButton=true;
sh.getRange(`A9:O9`).format={fill:'#203F4B',font:{bold:true,color:'#FFFFFF'},rowHeight:31,wrapText:true};
sh.getRange(`A10:O${last}`).format={rowHeight:66,wrapText:true,verticalAlignment:'center'};
for(const [col,width] of Object.entries({A:7,B:43,C:17,D:10,E:10,F:9,G:10,H:9,I:9,J:12,K:12,L:37,M:13,N:66,O:15}))sh.getRange(`${col}1:${col}${last}`).format.columnWidth=width;
sh.getRange(`D10:J${last}`).format.font.color='#2166B1';
sh.getRange(`D10:I${last}`).setNumberFormat('0;[Red](0);–');
sh.getRange(`J10:K${last}`).setNumberFormat('$0.00;[Red]($0.00);–');
sh.getRange(`L10:L${last}`).format.font={size:9,color:'#287277'};
sh.getRange(`M10:M${last}`).format.font.size=9;
sh.getRange(`C10:C${last}`).conditionalFormats.add('containsText',{text:'HOLD',format:{fill:'#FCE3C9',font:{color:'#865422',bold:true}}});
sh.getRange(`C10:C${last}`).conditionalFormats.add('containsText',{text:'BUY',format:{fill:'#D8EDE4',font:{color:'#1D5A44',bold:true}}});
sh.getRange(`C10:C${last}`).conditionalFormats.add('containsText',{text:'OWNED',format:{fill:'#E4ECF3'}});
sh.getRange(`E10:G${last}`).dataValidation={rule:{type:'whole',operator:'between',formula1:0,formula2:1000}};
const newRow=10+rows.findIndex(q=>q.id==='P06');sh.getRange(`A${newRow}:O${newRow}`).format.rowHeight=100;
sh.freezePanes.freezeRows(9);sh.freezePanes.freezeColumns(2);
wb.recalculate();
const before=Number(sh.getRange('E3').values[0][0]);
if(Math.abs(before-35.72)>0.005)throw Error(`Unexpected first-purchase subtotal ${before}`);
// Meaningful edit check: receiving one belt removes exactly its cost.
sh.getRange('F12').values=[[1]];wb.recalculate();
const after=Number(sh.getRange('E3').values[0][0]);
if(Math.abs(before-after-7.09)>0.005)throw Error('Owned quantity did not reduce purchase subtotal');
sh.getRange('F12').values=[[0]];wb.recalculate();
const inspect=await wb.inspect({kind:'region',sheetId:'BOM',range:'D9:K16',maxChars:3000,tableMaxRows:8,tableMaxCols:8});
const values=sh.getRange(`A1:O${last}`).values;
const errors=values.flat().filter(v=>typeof v==='string'&&/^#(REF!|DIV\/0!|VALUE!|N\/A|NAME\?|NUM!)/.test(v));
if(errors.length)throw Error(errors.join(','));
await fs.writeFile(path.join(root,'checks/bom-check.json'),JSON.stringify({subtotal_usd:before,owned_quantity_edit_check:true,formula_errors:errors,rows:rows.length,inspect},null,2));
const xlsx=await SpreadsheetFile.exportXlsx(wb);await xlsx.save(path.join(root,'BOM.xlsx'));
const preview=await wb.render({sheetName:'BOM',range:'A1:O16',scale:1,format:'png'});
await fs.writeFile(path.join(root,'.local/bom-preview.png'),new Uint8Array(await preview.arrayBuffer()));
const changed=await wb.render({sheetName:'BOM',range:`A${last-3}:O${last}`,scale:1,format:'png'});await fs.writeFile(path.join(root,'.local/bom-drive-preview.png'),new Uint8Array(await changed.arrayBuffer()));
console.log(JSON.stringify({file:'BOM.xlsx',rows:rows.length,first_purchase_priced_subtotal:before,checks:'passed'}));
