from pathlib import Path
import json
R=Path(__file__).resolve().parent
def read(n):return json.loads((R/n).read_text())
def save(n,x):(R/n).write_text(json.dumps(x,indent=2)+'\n')
p=read('parameters.json');p['revision']='vehicle-integrated-drive-end-v2'
p['revision_reason']='Vehicle end section is the first substantial print; use the same registered flange for clamped tests and final body assembly. Wheel/tire work deferred.'
q=p['integrated_drive'];q.update(input_rails_y=[50.5,104],input_spine_x_from_axis=[-23,18.5],input_spine_floor_z_axle=[-29,-25],carriage_fastener_xy_from_input_axis=[[-18,56],[13,56],[-18,84],[13,84]],carriage_fastener='4 x M4 hex-head bolts, washer and captive nut; side-wrench approach below the belt, actual tool sweep to verify',body_interface_relief={'min_xyz_axle':[24,38,-40],'max_xyz_axle':[73,50,-17]},servo_case_min_xyz_axle=[39.672255,8,-30],servo_case_size_xyz=[20,40.5,40.5],servo_case_orientation='90 degrees about output axis relative to previous article. Output offset and ears still unmeasured.',saddle_attachment='4 x M3 clearance at X=input axis +/-14.5, Y12/42; measured saddle/ear retainers and locking nuts still to detail',parent_body_status='Matching short body-interface segment modeled. Rest of whole-body packaging has not been updated or cleared.',wheel_bearing_span_mm=48,input_bearing_span_mm=27,print_material='PETG starting candidate; fit review, no strength/temperature qualification')
f=p['drive_article'];f['status']='Historical wheel/bench article. Current drive structure is integrated_drive; wheel/tire printing deferred.'
f['frame_base_status']='SUPERSEDED: rectangular bench frame removed from current native assembly; no transfer to a different vehicle frame required.'
p['printer_verified_reference']['wheel_process']='Historical wheel set was successfully sliced offline for X2D main nozzle; wheel/tire printing now deferred. See test-record.json.'
save('parameters.json',p)
s=read('parts-sources.json');s['current_packaging_revision']=p['revision']
for x in s['other_parts']:
 if x['item'].startswith('Ground 8 mm'):x['lengths_mm']=[110,110,49,49];x['action']='110 mm wheel shafts and 49 mm input shafts are current geometry; prepared groove/flat/retention and supplier drawing remain HOLD.'
for x in s['bom']['rows']:
 if x['stage']=='BUY FIXTURE':x['stage']='BUY ONE SIDE'
 if x['id'] in ['P02','H04','H05','H06']:x.update(stage='DEFER WHEEL',first_stage_qty=0);x['notes']='Wheel/tire selection and printing deferred by user. '+x['notes']
 if x['id']=='M08':x['notes']='49 mm shaft geometry Y55..104, with prepared end groove/retaining ring. Groove, shims, adapter and supplier remain HOLD; do not order a wrong specification.'
 if x['id']=='P01':x['notes']='Native HTD3M tooth geometry exists. Bought belt fit, shaft attachment, clutch plate/bush and loaded operation remain unqualified.'
 if x['id']=='P03':x['notes']='Current end section uses D159 shell, D151 register and four M4 body mounts. Separate main drum and electronics lid remain later prints; do not duplicate the end section.'
 if x['id']=='H01':x['notes']='Per drive: four M4 body bolts, eight M4 bearing-cap bolts and four M4 carriage bolts plus nuts/washers. Four M3 cover screws and four M3 saddle screws also required. Lengths/locking/tool fit remain to verify. Wheel hardware deferred separately.'
if not any(x['id']=='P06' for x in s['bom']['rows']):
 template=s['bom']['rows'][12].copy();template.update(id='P06',item='Reusable vehicle drive end section + input spine',model='drive-end-section.nbcad; PETG fit candidate',stage='FIT REVIEW',vehicle_qty=2,first_stage_qty=1,owned_qty=0,ordered_qty=0,pack_qty=1,pack_price_usd=None,source='Local native CAD: drive-end-section.nbcad',checked='2026-09-13',notes='Two structural meshes supplied for unpowered fit review after bearing coupon. Same carrier clamps for testing and bolts to the drum. Caps/saddle/guard/shaft interfaces still need completion before a powered assembly.',group='Printed drive')
 s['bom']['rows'].append(template)
save('parts-sources.json',s)
plan=(R/'PLAN.md').read_text()
start=plan.index('## The proposed first substantial print');end=plan.index('## Datum, width and supported drive')
new='''## First substantial print: the actual vehicle end section

Build one drive end section that stays on the vehicle after testing. The previous rectangular bench base and rectangular cover are superseded. The new native assembly is `drive-end-section.nbcad`, generated by `integrate_drive.py` from the common parameters and retained native belt mechanism. `drive-end-structure.nbcad` is its structural subassembly; it is not a second vehicle design. Review images show actual native CAD meshes, not a physically built mechanism or a screenshot of an open desktop document.

The carrier is a D159 curved PETG starting design inside the proposed D160 drum, with 3.5 mm curved skin, two integral wheel-bearing bulkheads and fixed rails for a removable input spine. Its D151 x2 mm pilot enters a D151.3 trial socket in the central body's matching bulkhead. Four M4 bolts on a D138 circle attach from inside the body to captive nuts in the carrier. The pilot locates the joint; bolts clamp it. The flange and matching body segment have the same lower-front opening to clear the inward-projecting motor carriage. This is a real mating interface, not a flat bench plate to discard later. Keep the main body unprinted until this interface and the complete hardware envelopes are checked.

For a clamped test, remove the short green mating-body reference segment. Apply padded clamps to opposed upper areas of the mounting flange/pilot faces, with a separate bench reaction stop and enough height for the eventual wheel to clear the bench. Clamps must bear on the flange, clear the bolt holes, and leave the lower-front service opening free. Do not grip bearing caps or the moving input spine. Clamp dimensions, force and support arrangement must be checked on the actual bench; there is no assumed clamp or load rating. The flange does the same locating/support job in both the bench setup and final vehicle. No sacrificial tabs or separate printed test chassis.

The motor and its two input bearings share one tension-adjustable spine. The published 40.5 x20 x40.5 case is turned 90 degrees around the output axis: its trial box is X39.672..59.672, Y8..48.5, Z-30..10.5 relative to the axle. Its longer dimension now lies vertically, clearing the wheel-bearing rib. The output axis remains at X49.672/Z0, so the 24/48 belt arrangement is retained. Ear geometry and the output offset inside the case are still unmeasured; do not mistake this box for a complete fitted servo. A small replaceable saddle attaches to common M3 lands, so measurement changes primarily affect that saddle and the torque adapter, rather than the curved load-bearing carrier.

The spine has a 4 mm floor, short reinforcing ribs and two split bearing seats. Four M4 slots allow +/-1.5 mm X adjustment. Fixed rails start behind the servo, avoiding a collision with its lower case and saddle. Carriage bolt rows are Y56/84, X31.672/62.672. Use low hex-head M4 bolts and a thin side-entry spanner below the belt for the rear row; a vertical driver there would cross the belt. Washer/head/nut dimensions, actual spanner sweep, bolt lengths and locking method remain an assembly-fit gate. Tension is set with both bearing caps secured; recheck shaft freedom after tightening all four carriage bolts. Tension must not be imposed by tilting a shaft or flexing its bearing posts.

The round removable cover ends at Y105 and uses four recessed M3 countersunk fasteners. The bearing bulkheads form portions of the end wall; their mating windows, shaft passages and wheel-shield overlap remain to finish before power. Access from the opened body is needed for body bolts and inboard retention. Remove the cover and wheel/hub as necessary for outward bearing-cap access. Fit the carrier's captive nuts first, install shafts/bearings/clutch/belt with caps removed, set endplay independently of clutch adjustment, then set tension and install the cover. No component should be trapped behind a permanently joined wall.

The two structural STLs in `first-prints/drive-end-section/` are **unpowered fit-review candidates**, not a complete powered assembly. They are the intended vehicle components and can be retained if the first fit passes. Begin with the bearing/fastener coupon, verify the holes, mating register and assembly access, then decide whether to print the full carrier and spine. Inspect support in the actual X2D profile and material before printing. The model has not been strength-tested; local fillets, captive-nut roof thickness, cap registration and repeatable joint preload still need physical/assembly review before applying drivetrain loads.

**Wheel and tire are deferred.** The earlier wheel STLs and offline slice records remain historical design evidence. Their approximately 505 g /20 h estimate per set is a reason to resolve this mechanism first, not a current print recommendation. Purchased tire versus printed TPU remains open. A test lever or later wheel attaches to the same purchased 8 mm shaft hub after its retention is complete; no rubber is needed for dimensional or free-rotation checks.

![Vehicle drive end section](C:/Users/jeffg/Documents/noBS-CAD/Roller-300/drive-end-section-overall.png)

![Drive end section with cover removed](C:/Users/jeffg/Documents/noBS-CAD/Roller-300/drive-end-section-drive.png)

'''
plan=plan[:start]+new+plan[end:]
plan=plan.replace('owned-injora-drive-article-v1. Actual editable CAD and wheel-fit print set','vehicle-integrated-drive-end-v2. Actual editable CAD and reusable drive-end fit candidates')
a=plan.index('`parameters.json` is the parameter source;');b=plan.index('\n\n## Owned servo',a)
plan=plan[:a]+'''`parameters.json` is the parameter source; `parts-sources.json` and `BOM.xlsx` track parts; `test-record.json` records checks. Current drive CAD is `drive-end-section.nbcad`. The older `drive-article.nbcad` retains the wheel study and superseded bench structure; `Roller-300.nbcad` is an earlier whole-vehicle envelope study with the superseded goBILDA hull. Neither older assembly establishes the new servo/body fit. There is one canonical plan. CAD application source is untouched.'''+plan[b:]
a=plan.index('The rectangular 114');b=plan.index('\n\nChoose this live-shaft',a)
plan=plan[:a]+'''The current curved carrier and circular cover replace the over-radius rectangular bench parts. Bearing seats and shaft positions now belong to the proposed final body end section. The unchanged outward shaft/hub stack preserves the proposed 300 mm width; full tire deformation/runout and complete vehicle packaging remain unverified.'''+plan[b:]
plan=plan.replace('The bench module is one side','The vehicle end section is one side')
plan=plan.replace('integral bearing blocks/rails → frame','integral bearing bulkheads → curved carrier → registered/bolted central body')
plan=plan.replace('Continue independent wheel/guard work while waiting.','Continue the common carrier, supported shafts and service interfaces while waiting.')
plan=plan.replace('1. Fit the bearing coupon, then the full wheel print set to the purchased hub. Check runout/endplay, screw engagement, tire keys/beads and tool access. Weigh parts and record slicer/material settings. No powered load test yet.','1. Fit the bearing/fastener coupon, then review and print the reusable carrier/spine. Check the body register, nut access, bearing alignment/endplay, carriage sweep and clamp interface. Weigh actual prints. Wheel/tire printing is deferred. No powered load test yet.')
plan=plan.replace('Clamp the complete one-side guarded fixture','Clamp the complete one-side guarded vehicle end section')
plan=plan.replace('Only then transfer qualified dimensions into the round body and perform','Retain that qualified end section, print its mirrored mate after any corrections, bolt them to the matching round body, and perform')
plan=plan.replace('**Battery/electronics/harness last within retained space.**','**Battery/electronics/harness last within retained space.** The rotated servo case currently intrudes into the old battery allowance by about 2.33 mm in X and 4 mm in Z where their Y ranges overlap. That allowance is not a measured pack. Do not claim the battery fits or shift it rearward without checking the circular wall. Resolve the actual small-pack dimensions before freezing the central body; this drive revision does not establish whole-body fit.')
(R/'PLAN.md').write_text(plan)
t=read('test-record.json');t['current_revision']=p['revision'];t['gates']['new_clutch_retention_packaging']='Current ComInTec candidate envelope fits between output bearings; plate/bush/retention qualification still OPEN. Earlier overlap warning superseded.'
t['gates']['printer_slicer_footprint']='Historical wheel set passed offline X2D slice placement; new carrier/spine not yet sliced or physically printed.'
t['gates']['complete_one_side_detail_and_guarding']='OPEN - reusable carrier/body interface modeled; specific servo, clutch, retention, tool and guard interfaces remain held.'
t['drive_end_section']={'design':'Vehicle carrier and input spine; clamp via final body flange, retain for vehicle after qualification','current_native':'drive-end-section.nbcad','wheel_tire_work':'DEFERRED by user','CAD_check_record':'drive-end-section-checks.json','physical_tests':'NOT PERFORMED','powered_release':False}
t['current_CAD_checks']['article']='drive-end-section-checks.json';save('test-record.json',t)
b=(R/'bom.mjs').read_text().replace('ONE integrated wheel/belt article.','ONE reusable vehicle drive end section.').replace('Priority: wheel support / servo','Priority: reusable wheel support / servo');(R/'bom.mjs').write_text(b)
print('Updated the canonical plan, common parameters and existing BOM/test records')
