"""Reconcile the S20 source record; purchase quantities never imply a purchase."""
from pathlib import Path
import copy,json,math,hashlib
R=Path(__file__).resolve().parents[1];f=R/'parts-sources.json';p=json.loads(f.read_text(encoding='utf-8'))
p.setdefault('historical_bom_before_adversarial_review',copy.deepcopy(p['bom']))
p.setdefault('historical_other_parts_before_adversarial_review',copy.deepcopy(p['other_parts']))
rows=p['bom']['rows'];by={r['id']:r for r in rows}
base='https://www.servocity.com/'
def update(i,**kw):
 by[i].update(kw)
 if i!='H21':by[i]['checked']='2026-10-06'
 if by[i]['stage'].startswith('BUY') and 'servocity.com/' in by[i]['source']:by[i].update(supplier='ServoCity',source_status='EXACT CATALOG MATCH')
update('M08',item='Input REX shaft with factory Eclip',model='2106-4008-0480; 8mm REX x48, M4 tapped ends',pack_price_usd=4.29,source=base+'2106-series-stainless-steel-rex-shaft-8mm-diameter-48mm-length/',notes='S20 actual manufacturer STEP. Nominal Y46.5..94.5; factory clip49.8..50.5. Positive AF7.3 printed bores drive both adapter and pulley. No input pinch screws or fabricated thin collar.')
update('M11',item='Printed servo bridge and positive REX horn adapter',model='S20; H25T horn + AF7.3 keyed input',notes='Native shared datums repaired, four servo ear and two bridge nuts captured. Adapter has factory Eclip pocket/radial window; two input friction clamps removed. Printed pieces counted in current print-set manifest/material estimate.')
update('P01',item='Printed positive REX input and rigid output pulleys',model='24T /48T, 3M pitch, 9mm belt',notes='S20 positive AF7.3 input bore replaces friction clamp. Integral R5.5 input lands locate pulley between bearing inner races with0.4mm total nominal endplay. Output bolts to purchased Sonic hub. No mechanical torque limiter.')
update('P06',model='S20 carrier, roof-open section,4 retainers,servo bridge and positive REX horn adapter',notes='11 connected pieces per one-drive fit set; wheel separate. Native CAD exports and slicer manifest in first-prints/adversarial-fit-2026-10-06. Four captured servo ear nuts plus two side-loaded bridge nuts; rounded posts and unobstructed lower driver passages.')
update('M18',item='Input and output inner-race metal spacers, 6mm',model='1522-0010-0060; 8ID x10OD x6; 4-pack',first_stage_qty=2,vehicle_qty=4,pack_qty=4,pack_price_usd=3.49,stage='BUY FIT CHECK',source=base+'1522-series-8mm-id-spacer-10mm-od-6mm-length-4-pack/',notes='One input rear spacer Y88..94 and one output mouth spacer Y105..111 per drive. Stock manufacturer STEP replaces the unsourced 6mm clamp collar. One four-pack covers both drives.')
by['M18'].pop('reference_source',None)
update('M19',item='Input rear metal shim, 0.5mm',model='2807-0811-0500; 8ID x11OD x0.5; 12-pack',pack_qty=12,pack_price_usd=2.69,stage='BUY FIT CHECK',source=base+'2807-series-stainless-steel-shim-8mm-id-x-11mm-od-0-50mm-thickness-12-pack/',notes='One per drive Y94..94.5. Actual manufacturer STEP; old unsourced 1.7mm stack retired. Receiving endplay checked before tightening; no outer-race preload.')
update('M20',item='Output mouth metal spacer, additional 2mm',model='1522-0010-0020; 8ID x10OD x2; 4-pack',pack_qty=4,pack_price_usd=2.79,stage='BUY FIT CHECK',source=base+'1522-series-8mm-id-spacer-10mm-od-2mm-length-4-pack/',notes='Y111..113, together with M18 output 6mm spacer forms the required 8mm stop. Actual manufacturer STEP. Supersedes unsourced 11OD x8 spacer; avoids the ambiguous 8mm product URL currently labeled 9mm.')
update('M05',notes='Exact Hyper Hub. S20 stock 6mm +2mm spacers, total8mm, Y105..113; D10 nominal manufacturer models. Rear hub abutment/endplay still needs receiving fit.')
update('H11',vehicle_qty=44,first_stage_qty=22,notes='22 per drive: bearing retainers16 + servo ears4 + upper bridge2. Both input pinch nuts retired. Plain M3 nuts in H21; native pockets tested with AF5.5 x2.4 nominal hardware.')
update('H15',vehicle_qty=0,first_stage_qty=0,stage='RETIRED INPUT CLAMP',notes='S20 positive REX shaft removes both input pinch screws and nuts. Do not order for the active drivetrain.')
update('H17',model='632296; M3x0.5 pan head16mm, Phillips #1; 6-pack',pack_qty=6,pack_price_usd=1.99,stage='BUY FIT CHECK',source=base+'3mm-x-16mm-zinc-plated-metric-pan-head-phillips-machine-screws/',notes='Two per drive. Through-hole and side-loaded AF6 captured nuts at Z128.7..131.5. Bolt seat143.25, tip127.25; full nominal nut engagement. Unrecessed head D6 x2.5 clearance envelope; check received head and driver.')
by['H17'].pop('purchase_bundle_id',None)
update('H21',notes='One kit charged once for the plain M3 nuts H11; 22 per drive. Bridge uses separately sourced M3x16 pan screws H17. Long screws in this kit are spare; use existing compatible plain nuts if already owned and credit the quantity.')
update('H23',notes='Use a compatible low-profile center screw from servo/horn hardware if it seats without bottoming. Head seatY43.6; D5.7 x1.65 head ends45.25; nominal shaft begins46.5 (1.25mm gap, conservative vendor STEP gap0.883mm). Length/thread depth remain a receiving check. Install before input shaft.')
update('H24',notes='Four per drive. M4x6 ISO7380-1 heads atY45.1..47.3; nominal metal engagement2.5mm into the purchased horn. Driver access checked on bench. Positive REX replaces pinch, with factory Eclip insertion through adapter side window.')
for i,item,model,price,url,notes in [
 ('H25','Input REX end-retention screw','2802-0004-0008; M4x0.7 button head8mm;25-pack',3.19,'2802-series-zinc-plated-steel-button-head-screw-m4-x-0-7mm-8mm-length-25-pack/','One per drive; washer thickness1.5 leaves nominal6.5mm M4 engagement. Actual manufacturer STEP. Tighten against shaft end and metal stack, checking free rotation/endplay. Thread phase in CAD is a reference, not a measured thread fit.'),
 ('H26','Input end-retention steel washer','2801-0004-0011; 4ID x11OD x1.5;25-pack',2.29,'2801-series-zinc-plated-steel-washer-4mm-id-x-11mm-od-25-pack/','One per drive Y94.5..96.0; actual manufacturer STEP, OD10.9. End screw and washer retain rear spacer/shim on the bearing inner race; front Eclip is captured in the printed adapter.')]:
  r=dict(id=i,item=item,model=model,vehicle_qty=2,first_stage_qty=1,owned_qty=None,ordered_qty=0,pack_qty=25,pack_price_usd=price,stage='BUY FIT CHECK',source=base+url,checked='2026-10-06',notes=notes,group='Drivetrain',supplier='ServoCity',source_status='EXACT CATALOG MATCH')
  if i in by:by[i].update(r)
  else:rows.append(r);by[i]=r
def total(key,credit=True):return round(sum(math.ceil(max((r.get(key) or 0)-((r.get('owned_qty') or 0)+(r.get('ordered_qty') or 0) if credit else 0),0)/r['pack_qty'])*r['pack_price_usd'] for r in rows if isinstance(r.get('pack_price_usd'),(float,int))),2)
p['bom'].update(priced_first_stage_subtotal_usd=total('first_stage_qty'),priced_vehicle_purchase_subtotal_usd=total('vehicle_qty'),priced_vehicle_purchase_without_owned_credit_usd=total('vehicle_qty',False),scope='S20 positive REX input, rigid 2:1 belt drivetrain; unpowered one-drive roof-open fit first.',sourcing_checked='2026-10-06',sourcing_status='New REX shaft/retention/spacers and bridge screws checked against ServoCity catalog and available STEP on2026-10-06. Other offers retain recorded dates. Carrier washers, wheel fasteners and center-screw length remain receiving/source checks.')
p['current_packaging_revision']='adversarial-review-2026-10-06'
p['other_parts']=[dict(item=r['item'],quantity=r['vehicle_qty'],model=r['model'],classification=r['stage'],source=r['source'] or None,action=r['notes']) for r in rows]
p['sourcing_revision']['unresolved']=[i for i in p['sourcing_revision']['unresolved'] if i not in ['M18','M19','M20']]
p['adversarial_revision']=dict(date='2026-10-06',revision='S20',source_sha256=hashlib.sha256((R/'Roller-300.nbcad').read_bytes()).hexdigest(),findings_fixed=['Shared datum moved repeatedly; mismatched reference servo ears','Bridge vertical bores outside bridge and missing captures','Lower servo bolt and driver blocked by carrier base','Rotating pinch ear touched carrier','M3 pulley nut cannot be enclosed in its 5mm hub','Unsourced thin collar and 1.7mm shim stack','Keyed pulley required axial stops; integral inner-race lands added','Mirrored stock thread references replaced by proper rotation'],new_input='Stock REX48 with factory Eclip; positive printed AF7.3 bores; stock rear6mm spacer,0.5mm shim,1.5mm washer,M4x8 end screw; integral pulley lands with0.4mm total nominal play',release='Unpowered one-drive roof-open receiving and assembly test. Powered loads, belt tooth qualification and complete barrel service access remain open.')
p.setdefault('historical_cost_review_before_adversarial',copy.deepcopy(p['cost_review']))
slices=json.loads((R/'first-prints/adversarial-fit-2026-10-06/slice-checks.json').read_text());assert slices['passed']
manifest=json.loads((R/'first-prints/adversarial-fit-2026-10-06/source.json').read_text())
qty={q['name']:q['quantity'] for q in manifest['parts']};mass=sum(q['grams']*qty[q['part']] for q in slices['parts']);wheel=next(q['grams'] for q in slices['parts'] if q['part']=='left-wheel-axle-vertical')
p['cost_review'].update(date='2026-10-06',one_drive_priced_purchase_usd=total('first_stage_qty'),two_drive_priced_purchase_usd=total('vehicle_qty'),two_drive_priced_purchase_without_owned_credit_usd=total('vehicle_qty',False),priced_first_stage_purchase_usd=total('first_stage_qty'),priced_two_drive_purchase_usd=total('vehicle_qty'),current_fit_set_grams_including_supports=mass-wheel,current_wheel_slice_grams_including_supports=wheel,first_stage_print_kg_including_wheel=mass/1000,print_mass_scope='11 current S20 native pieces from warning-free individual X2D PETG slices; supports included, tread excluded. Combined ten-part plate differs slightly in support/travel mass.',complete_vehicle_unpriced_rows=[q['id'] for q in rows if q.get('vehicle_qty') and not isinstance(q.get('pack_price_usd'),(int,float)) and not q['stage'].startswith(('INCLUDED','RETIRED','OWNED'))],unknown_vehicle_quantity_rows=[q['id'] for q in rows if q.get('vehicle_qty') is None])
for q in p['cost_review']['recommendations']:
 if q['priority']==1:q.update(action='Retain purchased metal H25T horn,608 bearings, metal output hubs and independent wheel shafts; use stock keyed REX48 input.',status='Implemented in S20; receiving fit and powered loads untested.')
 if q['priority']==2:q.update(action='Remove both input pinch clamps and custom thin collar/shim stack; use keyed REX48 with factory Eclip and stock rear retention.',status='Implemented in S20, axial stops and nominal geometry checked.')
 if q['priority']==3:q.update(action='Use stock6mm +2mm D10 output inner-race spacers for the8mm mouth stop.',status='Implemented from actual vendor STEP. The8mm product URL is ambiguously labeled9mm; no reliance on that listing.')
f.write_text(json.dumps(p,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'rows':len(rows),'first_priced':total('first_stage_qty'),'two_drive_priced':total('vehicle_qty')}))
